// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcS68G2pp3sgN7xGWswOv2iLN4ZifLf3g',
    appId: '1:817507341190:web:3fb9ebec6133abfbddd207',
    messagingSenderId: '817507341190',
    projectId: 'flashchat-681b5',
    authDomain: 'flashchat-681b5.firebaseapp.com',
    storageBucket: 'flashchat-681b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvFDNhot9ujl3X3OX-VbGNS1lbA2Sy2g',
    appId: '1:817507341190:android:2d027f09355adcf6ddd207',
    messagingSenderId: '817507341190',
    projectId: 'flashchat-681b5',
    storageBucket: 'flashchat-681b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA41MubL8OmIa78k-6sR8H729vLCe4UgQ',
    appId: '1:817507341190:ios:43003d17bb5cdd36ddd207',
    messagingSenderId: '817507341190',
    projectId: 'flashchat-681b5',
    storageBucket: 'flashchat-681b5.appspot.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA41MubL8OmIa78k-6sR8H729vLCe4UgQ',
    appId: '1:817507341190:ios:43003d17bb5cdd36ddd207',
    messagingSenderId: '817507341190',
    projectId: 'flashchat-681b5',
    storageBucket: 'flashchat-681b5.appspot.com',
    iosBundleId: 'com.example.flashChatStartingProject',
  );
}
